codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project: off
    patch:
      default:
        target: 75%

ignore:
  - "packages/hevy-client/src/generated/**/*" # Ignore generated API output
