export type {
	BodyMeasurement,
	CreateCustomExerciseRequestBody,
	CustomExerciseTypeKey,
	CustomExerciseTypeKey as CustomExerciseTypeEnumKey,
	DeletedWorkout,
	EquipmentCategoryKey,
	EquipmentCategoryKey as EquipmentCategoryEnumKey,
	Exercise,
	ExerciseHistoryEntry,
	ExerciseTemplate,
	GetV1BodyMeasurementsStatus200 as GetV1BodyMeasurements200,
	GetV1BodyMeasurementsStatus200,
	GetV1BodyMeasurementsDateStatus200 as GetV1BodyMeasurementsDate200,
	GetV1BodyMeasurementsDateStatus200,
	GetV1ExerciseHistoryExercisetemplateidStatus200 as GetV1ExerciseHistoryExercisetemplateid200,
	GetV1ExerciseHistoryExercisetemplateidStatus200,
	GetV1ExerciseTemplatesStatus200 as GetV1ExerciseTemplates200,
	GetV1ExerciseTemplatesStatus200,
	GetV1ExerciseTemplatesExercisetemplateidStatus200 as GetV1ExerciseTemplatesExercisetemplateid200,
	GetV1ExerciseTemplatesExercisetemplateidStatus200,
	GetV1RoutineFoldersStatus200 as GetV1RoutineFolders200,
	GetV1RoutineFoldersStatus200,
	GetV1RoutineFoldersFolderidStatus200 as GetV1RoutineFoldersFolderid200,
	GetV1RoutineFoldersFolderidStatus200,
	GetV1RoutinesStatus200 as GetV1Routines200,
	GetV1RoutinesStatus200,
	GetV1RoutinesRoutineidStatus200 as GetV1RoutinesRoutineid200,
	GetV1RoutinesRoutineidStatus200,
	GetV1WorkoutsStatus200 as GetV1Workouts200,
	GetV1WorkoutsStatus200,
	GetV1WorkoutsCountStatus200 as GetV1WorkoutsCount200,
	GetV1WorkoutsCountStatus200,
	GetV1WorkoutsEventsStatus200 as GetV1WorkoutsEvents200,
	GetV1WorkoutsEventsStatus200,
	GetV1WorkoutsWorkoutidStatus200 as GetV1WorkoutsWorkoutid200,
	GetV1WorkoutsWorkoutidStatus200,
	GetV1BodyMeasurementsDateResponse as GetV1BodyMeasurementsDateQueryResponse,
	GetV1BodyMeasurementsDateResponse,
	GetV1BodyMeasurementsResponse as GetV1BodyMeasurementsQueryResponse,
	GetV1BodyMeasurementsResponse,
	GetV1BodyMeasurementsQuery,
	GetV1BodyMeasurementsDatePath,
	GetV1ExerciseHistoryExercisetemplateidQuery,
	GetV1ExerciseTemplatesQuery,
	GetV1RoutineFoldersQuery,
	GetV1RoutinesQuery,
	GetV1WorkoutsQuery,
	GetV1WorkoutsEventsQuery,
	MuscleGroupKey,
	MuscleGroupKey as MuscleGroupEnumKey,
	PaginatedWorkoutEvents,
	PostRoutineFolderRequestBody,
	PostRoutinesRequestBody,
	PostRoutinesRequestExercise,
	PostRoutinesRequestSet,
	PostRoutinesRequestSetTypeEnumKey,
	PostV1BodyMeasurementsStatus200 as PostV1BodyMeasurements200,
	PostV1BodyMeasurementsStatus200,
	PostV1ExerciseTemplatesStatus200 as PostV1ExerciseTemplates200,
	PostV1ExerciseTemplatesStatus200,
	PostV1RoutineFoldersStatus201 as PostV1RoutineFolders201,
	PostV1RoutineFoldersStatus201,
	PostV1RoutinesStatus201 as PostV1Routines201,
	PostV1RoutinesStatus201,
	PostV1WorkoutsStatus201 as PostV1Workouts201,
	PostV1WorkoutsStatus201,
	PostWorkoutsRequestBody,
	PostWorkoutsRequestExercise,
	PostWorkoutsRequestSet,
	PostWorkoutsRequestSetRpeEnumKey,
	PostWorkoutsRequestSetTypeEnumKey,
	PutBodyMeasurement,
	PutRoutinesRequestBody,
	PutRoutinesRequestExercise,
	PutRoutinesRequestSet,
	PutRoutinesRequestSetTypeEnumKey,
	PutV1BodyMeasurementsDateStatus200,
	PutV1RoutinesRoutineidStatus200 as PutV1RoutinesRoutineid200,
	PutV1RoutinesRoutineidStatus200,
	PutV1WorkoutsWorkoutidStatus200 as PutV1WorkoutsWorkoutid200,
	PutV1WorkoutsWorkoutidStatus200,
	Routine,
	RoutineFolder,
	Set,
	UpdatedWorkout,
	UserInfo,
	UserInfoResponse,
	Workout,
} from "./generated/client/types/index.js";
export {
	customExerciseType,
	equipmentCategory,
	muscleGroup,
	postRoutinesRequestSetTypeEnum,
	postWorkoutsRequestSetRpeEnum,
	postWorkoutsRequestSetTypeEnum,
	putRoutinesRequestSetTypeEnum,
} from "./generated/client/types/index.js";
